name: Tests

on:
- push
- pull_request

# env:
#   TARGET_URL: "https://mzima.staging.ush.zone"

jobs:
  test:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.16.0-chrome89-ff86
    timeout-minutes: 30

    # strategy:
    #  fail-fast: false
      # limit to 1 in parallel because we are running against the same platform deployment
      # max-parallel: 1
    #  matrix:
    #    containers: [1, 2, 3]
    #    browser:
    #      - chrome
          # - firefox   # browser not found on the image?

    steps:
    - uses: actions/checkout@v3

    - name: Cypress run
      uses: cypress-io/github-action@v4

      with:
        browser: "${{matrix.browser}}"
        install-command: npm install
        record: false
        parallel: false
        start: npm start
        
      env:
          CYPRESS_ush_admin_email: "${{secrets.ush_admin_email}}"
          CYPRESS_ush_admin_pwd: "${{secrets.ush_admin_pwd}}"
          CYPRESS_ush_user_name: "${{secrets.ush_user_name}}"
          CYPRESS_ush_user_email: "${{secrets.ush_user_email}}"
          CYPRESS_ush_user_pwd: "${{secrets.ush_user_pwd}}"
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
